### ISSUE TITLE
The research does not find the pod I am looking for.

### ISSUE THREAD

**Issue by colasjojo** [CocoaPods/cocoapods.org#144]
This is my research https://cocoapods.org/?q=PDF
In the "in the name of the pod" section, the following pod  `OHPDFImage` does not appear.

**Comment by kylef** [comment]
It does show up, it's just rated lower than others mostly due to low popularity (not many stars etc) compared to `UIImage+PDF`.

![screen shot 2015-04-28 at 16 05 48](https://cloud.githubusercontent.com/assets/44164/7372799/a6a167a2-edc0-11e4-9305-19088eaa87f2.png)

**Comment by colasjojo** [comment]
OK, this is what I thought.

IMHO, this is not clear (bad design). Especially because it also says : "7 results". So I think all the results of my request are these 7 ones.

Solution : a link link "all the results".

Thanks !

**Comment by floere** [comment]
@colasjojo It's not bad design, it's just that the way we index, "OHPDFImage" is not findable via "PDF", since we did not account for all uppercase library name pieces. (Initially I considered https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html and https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html)

I'll think about how to best include this.

**Comment by colasjojo** [comment]
@floere I only meant to help by giving you my feedback!

**Comment by floere** [comment]
And you did. I'm just documenting the issue, what the problems are, and whether and how to fix them while making clear that e.g. @orta does not need to do anything here.

**Comment by floere** [comment]
So, all good :)

**Comment by floere** [comment]
After some/lots of thought, I included this case: https://cocoapods.org/?q=PDF 😊 :rocket:
Cheers!

**Comment by colasjojo** [comment]
+1
