### ISSUE TITLE
Centralize CocoaPods Web Properties

### ISSUE THREAD

**Issue by maclover7** [CocoaPods/cocoapods.org#176]
Would it make sense to combine all of CocoaPods' web properties (cocoapods.org, guides.cocoapods.org, trunk, feeds, search, metrics, stats) under one centralized Rails application? Most of the applications are structured very similarly to a Rails app (they have controllers / models), and are using different Rails gems (e.g. sprockets). Also, it would make local development easier to only have to clone one repo.

I've already started to work on this here: [maclover7/cocoa-united](https://github.com/maclover7/cocoa-united) and here: [maclover7/cocoapods-assets](https://github.com/maclover7/cocoapods-assets)

@segiddins @orta

**Comment by orta** [comment]
We've never really discussed the idea of merging all the repos, from my perspective it would feel a lot like trying to bundle multiple apps into one. For example:

* Guides is generates 50% of it's content from the source code from CocoaPods, and is statically generated in order to not have to keep that cached anywhere
*  Search is a [picky](http://florianhanke.com/picky/index.html) application
* Metrics runs regular rake tasks related to pulling in github stats for every pod, as well as providing an API for others
* Stats does the same but acts as a conduit to/from our analytics redshift instance

Personally I prefer having a collection of smaller focused sites that have a strong domain over a mono app. We built [Strata](https://github.com/cocoapods/Strata) as a web opposite for [Rainforest](https://github.com/cocoapods/rainforest/) to make bootstrapping and setting up easy.

**Comment by segiddins** [comment]
@maclover7 thanks for the suggestion, but we actually designed things this way on purpose. Since CocoaPods is run entirely by unpaid volunteers, keeping operational costs low is a high priority. Having each component be a single-task service is an easy way to do that -- it allows us to operate on heroku for almost no money, but with the equivalent of several hundred dollars a month worth of power. Additionally, we don't feel the need to use Rails -- for what we're doing, it's overkill.

So thanks for the suggestion, but I think we're going to be keeping things this way for the foreseeable future.

**Comment by maclover7** [comment]
Gotcha. :+1:

**Comment by kylef** [comment]
This is awesome. We can call this a monolith.
