### ISSUE TITLE
Search Result Missing "Expand" For Pod

### ISSUE THREAD

**Issue by Pretz** [CocoaPods/cocoapods.org#217]
I recently pushed a new pod called [`Strutter`](https://github.com/Pretz/Strutter) to trunk. When I view it in search results, it doesn't have an _Expand_ link, instead it has `Site`, `Docs`, and `Spec` links. Clicking on the name of the pod goes directly to the homepage defined in the spec rather than showing the Cocoapods detail view.

This looks the same as #155, so I waited a few days to see if it was simply an indexing/site generating issue. It's been five days since I pushed it now. Am I just impatient and it'll show up soon, or did I do something wrong or break something?

One other reference point: my [Cocoapods Owner Page](https://cocoapods.org/owners/3761) doesn't list `Strutter` even though `pod trunk info Strutter` shows me as the owner.

Thanks!

**Comment by floere** [comment]
Not quite sure what happened, but now it's there, so I am closing this (thanks for investigating!).

@orta Perhaps you want to do some forensics?

**Comment by orta** [comment]
It's fixed, likely was an issue with carthage / jazzy, most of which got fixed up this weekend.

**Comment by amadkhilji** [comment]
I'm facing the same issue with my pod `GoogleMobileAdsMediationUnity`. I can't expand it in cocoapods.org search. I'm seeing `Site`, `Docs`, and `Spec` instead of `Expand`. And when I click [GoogleMobileAdsMediationUnity](https://cocoapods.org/pods/GoogleMobileAdsMediationUnity), it takes me to the homepage. However my other pods are working fine.

Thanks!
Google Mobile Ads Mediation Team.
