### ISSUE TITLE
Add socks page

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#250]
![socks-web](https://cloud.githubusercontent.com/assets/49038/13026880/58ecf4ae-d230-11e5-8282-6a2716706dc2.png)

Ideas
 * The big CP section could animate sideways as a GIF
 * Water at the top could wave ( http://codepen.io/ryanmcnz/pen/EDtun ? )
 * The hanging socks at the top / bottom could rotate/sway

Other than that design files are in [the cocoapods.org sketch doc](https://github.com/cocoapods/design) in the design repo.

**Comment by alloy** [comment]
Great work on both the socks and the page, @orta :clap: 

It’s also very great that all the money goes to wateraid, but I’m not sure if mentioning CP v1 here is the best idea. I’d prefer a v1 wateraid drive that celebrates the actual v1 release and goes for maximum money, rather than an incentive to donate just $16,- (and maybe ask companies such as Google to donate?).

**Comment by orta** [comment]
I was thinking about this on the plane - I agree

On my phone, replies will be curt.

**Comment by orta** [comment]
Changed it to 

> CocoaPods was started in 2011. We are a community run project, with no large-scale corporate backing. We're often asked if we'd do something like t-shirts or hoodies. 
            
> We don't want to use CocoaPods' popularity to make money. So, we are making sure all profits go to charity.
