### ISSUE TITLE
Pod shown as not having tests when it does

### ISSUE THREAD

**Issue by dlo** [CocoaPods/cocoapods.org#255]
I just submitted a pods last weekend and CocoaPods.org (incorrectly) shows it as having no tests. Any pointers?

https://cocoapods.org/pods/KeyboardAdjuster

**Comment by orta** [comment]
[You have 1 test](http://metrics.cocoapods.org/api/v1/pods/KeyboardAdjuster) which I verified as being correct, [we don't show](https://github.com/CocoaPods/cocoapods.org/blob/master/views/pod.slim#L9) it on CocoaPods.org because that's going to give people a false sense of security that the Pod has test coverage. 

I think it's better for the whole ecosystem that we aim for higher :+1: - feel free to add a few more, then you get the tick :D

**Comment by dlo** [comment]
Fighting the good fight. Thanks @orta. I think I can add 4 more tests. 😉

Feature request: add a tooltip or some sort of explanation for what’s
required to get the checkmark.

**Comment by sochalewski** [comment]
@orta I have the same issue, but have more tests (you can find them in Example/Tests on GitHub repository). Could you please describe me how the algorithm works? I remember that when I had only a test target in the example app it was showing a checkmark, but then I added an app target and it's gone.

What can I do to get the checkmark back?

https://cocoapods.org/pods/TinySwift

**Comment by orta** [comment]
Tests are pretty easy to check - https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/testing_idealist.rb

- get all xcodeprojects in folder
- look through all test targets
- grab all objc/swift files
- run regexes for common test expectations
- add them up

**Comment by sochalewski** [comment]
@orta I definitely have a test target in .xcodeproj and it's visible through `xcodebuild -list`. Tests are also visible for Travis which runs tens of them, but metrics shows 1 test and no test expectations at all. Could that works this way, because I created the project with `pod lib create` using CP 1.1.0.rc.2 instead of stable one?

**Comment by orta** [comment]
Shouldn't be, try running cocoadocs locally and seeing what results it gives?

**Comment by sochalewski** [comment]
@orta Finally found time to update OS X preinstalled `ruby` and can run it locally.

```
From git://github.com/CocoaPods/Specs
 * branch            master     -> FETCH_HEAD

 Looking at TinySwift master 

 > Git download
Analyzing dependencies
Fetching podspec for `TinySwift` from `/Users/Piotr/Desktop/cocoadocs.org/activity/download/TinySwift/0.5.2/TinySwift`
Downloading dependencies
Installing TinySwift (0.5.2)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/p_/0y0cc9jn2zb4pr_w4q4g4q8h0000gn/T/xcodebuild-1B924D11-76DB-48B6-9B9C-391A4198D69C.log
Failed to generate documentation
appledoc version: 2.2.1 (build 1333)

Found 0 for Pods-TinySwift_Tests
* - http://cocoadocs.org/docsets/TinySwift/0.5.2/
Preview: "/Users/Piotr/Desktop/cocoadocs.org/activity/docsets/TinySwift/0.5.2/"
```

I'm not sure why is it looking for tests only in `Pods-TinySwift_Tests` when they're in `TinySwift_Tests`. I checked my other pod out and this one works well and looks through two targets:
```
Found 0 for Pods-SwiftCompressor_Tests
Found 2 for SwiftCompressor_Tests
```

How could it be fixed?

**Comment by blob8129** [comment]
@sochalewski could you tell, what command did you run actually ?

**Comment by blob8129** [comment]
I have the same problem https://cocoapods.org/pods/SequenceConverter
