### ISSUE TITLE
Bug: Deleted pods appear in search results

### ISSUE THREAD

**Issue by michalkonturek** [CocoaPods/cocoapods.org#286]
Deleted pods are displayed in the search results, eg. [`MKEventKit`](https://cocoapods.org/?q=mkeventkit)

![screen shot 2016-08-22 at 15 32 43](https://cloud.githubusercontent.com/assets/288030/17858643/638cb0c2-687e-11e6-8bab-76a054b4de45.png)

In case of [MKFoundation](https://cocoapods.org/pods/MKFoundation), it even has its own page despite of being deleted.

**Comment by orta** [comment]
This was only just deleted, the search index isn't instant - it's marked as deleted in the db

**Comment by floere** [comment]
We don't yet propagate deletions instantly - it takes up to 24h for them to disappear.

On Mo., 22. Aug. 2016 at 16:41 Michal Konturek

<
mailto:Michal Konturek <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Deleted pods are displayed in the search results, eg.
https://cocoapods.org/?q=mkeventkit
https://cloud.githubusercontent.com/assets/288030/17858643/638cb0c2-687e-11e6-8bab-76a054b4de45.png

In case of
https://cocoapods.org/pods/MKFoundation
, it even has its own page despite of being deleted.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/CocoaPods/cocoapods.org/issues/286
, or

**Comment by michalkonturek** [comment]
Thank you for the swift response. 

What about [MKFoundation](https://cocoapods.org/pods/MKFoundation)? It has been deleted a while ago and it still appears.

**Comment by orta** [comment]
it's not marked as deleted in our database:

![screen shot 2016-08-22 at 10 51 47 am](https://cloud.githubusercontent.com/assets/49038/17859140/7593c396-6856-11e6-9fdf-15dd3a73406a.png)

**Comment by orta** [comment]
Did you use `pod trunk delete` and it failed somehow?

**Comment by michalkonturek** [comment]
Yes. Every time I deleted something I got an error page.

**Comment by michalkonturek** [comment]
The pod is not listed when searching via command line tool and it does not exist in cocoapods specs repo.
