### ISSUE TITLE
post-shard Podspec URL isn't reflected in cocoapods.org

### ISSUE THREAD

**Issue by johnbushnell** [CocoaPods/cocoapods.org#314]
https://cocoapods.org/pods/KochavaTrackeriOSGK should take me to my pod page, but instead it redirects to the value set in s.homepage of the podspec.

Also when you search for the pod on cocoapods.org using the search option, you see the page in the list (currently listed 5 times though which doesn't seem right) and when you click on one of them it redirects to the s.homepage the same way.

**Comment by orta** [comment]
Hi there, as the [issue template requests](https://github.com/CocoaPods/cocoapods.org/blob/master/.github/ISSUE_TEMPLATE.md) - please consult the CocoaDocs repo about how to debug this.

**Comment by paynerc** [comment]
We are seeing the same issues with `https://cocoapods.org/pods/TwilioVideo`. When you go there, it immediately redirects you to our `homepage` from the podspec, `http://www.twilio.com/video`.

We provided a `documentation_url` in the podspec, `https://media.twiliocdn.com/sdk/ios/video/releases/1.0.0/docs`, however I see that CocoaDocs was still run anyways.

I followed the suggestions in the CocoaDocs issue template and I am not sure how relevant they are because we are providing our own documentation url anyways.

The other odd thing, the entry in the Cocoapods.org search page doesn't link to the podspec properly. If you hover over the `Spec` link, it is showing `https://github.com/CocoaPods/Specs/tree/master/Specs/TwilioVideo/1.0.0/TwilioVideo.podspec.json` which it cannot find. It is actually `https://github.com/CocoaPods/Specs/blob/master/Specs/1/d/9/TwilioVideo/1.0.0/TwilioVideo.podspec.json`

Any help getting this resolved would be greatly appreciated, @orta. We are announcing our 1.0 GA of TwilioVideo today and would like to have things in order when the announcements happen.

Thanks again!

**Comment by segiddins** [comment]
@paynerc a PR that fixes the URLs to the sharded ones would be appreciated!

**Comment by paynerc** [comment]
@segiddins If I had a clue as to why the following happened:

1. The link to the `https://cocoapods.org/pods/TwilioVideo` is being redirected to homepage, `http://www.twilio.com/video`
2. Documentation was generated by Cocoadocs, even with the presence of `documentation_url`
3. The spec link is pointing to the incorrect place

I would be happy to fix. But at present I am not sure where to begin looking.

I am also trying to resolve https://github.com/CocoaPods/trunk.cocoapods.org/issues/155 as we wanted to change the name associated with our account, but specifying the `name` param on subsequent registrations has no effect.

**Comment by segiddins** [comment]
Looking at the code seems to suggest we just haven't re-deployed to heroku in many months?

**Comment by segiddins** [comment]
https://github.com/CocoaPods/cocoapods.org/blob/master/assets/javascripts/search.config.js#L269
is what needs to be updated (the ruby stuff is correct, the JS just was never updated)

**Comment by paynerc** [comment]
Not sure if this is relevant:

```
  # Gets a Pod Page
  #
  get '/pods/:name/?' do
    STDOUT.sync = true
    result = metrics.where(pods[:deleted] => false, pods[:normalized_name] => params[:name].downcase).first
    unless result
      result = pods.where(pods[:deleted] => false, pods[:normalized_name] => params[:name].downcase).first
      halt 404, "404 - Pod not found" unless result

      # Support redirecting to the pods homepage if we can't do it.
      version = pod_versions.where(pod_id: result["id"], deleted: false).sort_by { |v| Pod::Version.new(v.name) }.last
      commit = commits.where(pod_version_id: version.id, deleted_file_during_import: false).first
      pod = Pod::Specification.from_json commit.specification_data
      redirect pod.homepage
    end

    @content = pod_page_for_result result
    slim :pod_page
  end
```

When we go to `https://cocoapods.org/pods/TwilioVideo`, we are being directed to the homepage... So both results are returning `nil`, and we get redirected... Now if I could just figure out why those results are `nil`...

**Comment by paynerc** [comment]
> Looking at the code seems to suggest we just haven't re-deployed to heroku in many months?

Are you suggesting that what is running isn't current, @segiddins ? Are there plans to deploy?

**Comment by paynerc** [comment]
I still maintain that there are a few issues going on here. 

The first is that when you try and navigate to the pod page directly, both queries are returning `nil` for the pod lookup. This is then causing the redirect to the site URL.

The second issue is indeed with the search results and display. For some reason when you issue this search `http://search.cocoapods.org/api/v1/pods.picky.hash.json?query=pod:twiliovideo`, the results do not contain the `cocoadocs` parameter. Since it does not have this parameter, it wants to render the non-expandable search results. And then that is causing the doc links to be wrong because from what I can tell, the search result JSON *never* contains a `documentation_url`... I searched the specs repo for pod specs with `documentation_url` and then issued queries against `search.cocoapods.org`, `documentation_url` doesn't appear.

So yes, it appears that there is a discrepancy in `search.config.js`, but my initial issue still appears to be data related. I should have `"cocoadocs": true` in the response, but that isn't coming across, and when I attempt to navigate to `https://cocoapods.org/pods/TwilioVideo` we get no love either.

I am continuing trying to troubleshoot this issue and will hopefully have PRs later.

**Comment by orta** [comment]
Sorry - I've been at a conference, I ran the cocoadosc code manually and it's working on your page now: https://cocoapods.org/pods/TwilioVideo

The search should update with `cocoadocs:true` soon, I request it to re-index.

**Comment by orta** [comment]
WRT the "Podspec" link, that does look

**Comment by orta** [comment]
https://github.com/CocoaPods/cocoadocs.org/pull/508 will "fix" this in the sense that things that could have stopped the `trunk:true` happening will be removed from the CocoaPods architecture

**Comment by paynerc** [comment]
Thank you for taking a look at this, @orta!

**Comment by orta** [comment]
I removed the link to the podspec in non-CocoaDocs results

**Comment by yasirmturk** [comment]
same issue https://cocoapods.org/pods/OpenALPRSwift
